theme: jekyll-theme-minimal
title: Stephanie Rotter
description: PhD Candidate in Sociolinguistics, Pragmatics, and Semantics
show_downloads: false
logo: /stephanierotter/stephanierotter.github.io/pic.jpg
